### ISSUE TITLE
compile and create libPCL-pxi.a

### ISSUE THREAD

**Issue by tstibor** [PixInsight/PCL#31]
Hello Juan,

I tried to compile from master the libPCL-pxi.a and run into error:

```
make -f ./makefile-x64 --no-print-directory
make[1]: *** No rule to make target 'x64/Release/HTMLEntity.o', needed by '"/home/tstibor/dev/astronomy/pixinsight/PCL/src/pcl/linux/g++/x64/Release"/libPCL-pxi.a'.  Stop.
Makefile:18: recipe for target 'all' failed
make: *** [all] Error 2
```

It looks like that in commit _f82a90e_ the auto-generated makefile included ` +../../HTMLEntity.cpp \` though the file `HTMLEntity.cpp` was not included in the commit. Tested one commit before (_7b977b6_)
and everything compiled and `libPCL-pxi.a` is created:

```
...
...
ar: creating /home/tstibor/dev/astronomy/pixinsight/PCL/src/pcl/linux/g++/x64/Release/libPCL-pxi.a
make -f ./makefile-x64 --no-print-directory post-build
cp "/home/tstibor/dev/astronomy/pixinsight/PCL/src/pcl/linux/g++/x64/Release"/libPCL-pxi.a /home/tstibor/dev/astronomy/pixinsight/PCL/lib
```

Cheers
 Thomas

**Comment by jconejero** [comment]
Hi Thomas,

This is now fixed in https://github.com/PixInsight/PCL/commit/8ec757cac5f03d83d955f15f46a807917c5aa8a9. Thank you for detecting this problem.

**Comment by tstibor** [comment]
Perfect, many thanks. I will close this issue.
